#!/bin/bash
# Quick reference commands for WeatherAI Vercel deployment

echo "🚀 WeatherAI - Vercel Deployment Quick Reference"
echo "=================================================="
echo ""
echo "📁 Project: Real-WeatherAi"
echo "🏠 Location: /home/kennedy/Downloads/weather"
echo "🎯 Platform: Vercel"
echo ""
echo "Quick Commands:"
echo "==============="
echo ""
echo "1. LOCAL DEVELOPMENT"
echo "   npm install          # Install dependencies"
echo "   npm run dev          # Start dev server (port 5173)"
echo "   npm run lint         # Check for errors"
echo "   npm run format       # Format code"
echo ""
echo "2. LOCAL PRODUCTION TEST"
echo "   npm run build        # Build for production"
echo "   npm run preview      # Preview production build"
echo ""
echo "3. GIT & DEPLOYMENT"
echo "   git add .            # Stage all changes"
echo "   git commit -m 'msg'  # Commit changes"
echo "   git push origin main # Push to GitHub"
echo "   # Then Vercel auto-deploys!"
echo ""
echo "4. DEPLOYMENT LINKS"
echo "   Vercel Dashboard: https://vercel.com/dashboard"
echo "   GitHub Repo:      https://github.com/kennedy-273/Real-WeatherAi"
echo "   Weather AI Docs:  https://weather-ai.co/docs"
echo ""
echo "5. ENVIRONMENT SETUP"
echo "   LOCAL:  .env.local (git-ignored, for local dev)"
echo "   VERCEL: Add WEATHER_AI_KEY in Project Settings"
echo ""
echo "📚 Documentation:"
echo "=================="
echo "   SETUP.md                      - Local development guide"
echo "   VERCEL_DEPLOYMENT.md          - Complete deployment guide"
echo "   DEPLOYMENT_CHECKLIST.md       - Step-by-step checklist"
echo "   MIGRATION_SUMMARY.md          - What changed & why"
echo ""
echo "✅ Configuration Status:"
echo "========================"
echo "   ✓ vercel.json          - READY FOR DEPLOYMENT"
echo "   ✓ vite.config.ts       - READY FOR DEPLOYMENT"
echo "   ✓ .env.local           - READY FOR LOCAL DEV"
echo "   ✓ .env.example         - READY (template)"
echo "   ✓ .vercelignore        - READY"
echo ""
echo "🎯 Next Steps:"
echo "==============="
echo "   1. npm run build       # Test build locally"
echo "   2. npm run preview     # Test production locally"
echo "   3. git push origin main # Push to GitHub"
echo "   4. Add WEATHER_AI_KEY to Vercel dashboard"
echo "   5. Visit your Vercel URL"
echo ""
echo "💡 Pro Tips:"
echo "============"
echo "   - Vercel auto-deploys when you push to GitHub"
echo "   - Check Deployments tab in Vercel dashboard for status"
echo "   - Redeploy if you change environment variables"
echo "   - Use npm run lint to find errors before pushing"
echo ""
echo "🆘 Troubleshooting:"
echo "==================="
echo "   Blank page?         → Check WEATHER_AI_KEY in Vercel"
echo "   No weather data?    → Check browser DevTools console"
echo "   Build fails?        → Run 'npm install' locally"
echo "   API errors?         → Check /api/weather in Network tab"
echo ""
echo "==============================================="
echo "Ready to deploy? Follow DEPLOYMENT_CHECKLIST.md!"
echo "==============================================="
